### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by kungfoolabs** [speakup-xteam/speak-up-android#1]
Hey guys!

Great start on your idea. Love the initial wireframes and really appreciate the effort you guys made to resolving and coming up with an idea even after losing a team member. Really proud of you guys. I really really like this idea. I think that learning a language is something that requires a lot of dedication and time which will result in high usage and retention of users who download the app. Overall, I like how you guys already thought of the onboarding process and bucketing user into their experience level. What I want you guys to focus on though is what the core experience will be. Right now, the experience I am seeing is that this is a match making app but it doesn't **enforce** the learning of the language. Meaning, that the chatroom experience is just like a Google Hangout or Skype experience. 

### Product
- I think you guys have a good initial onboarding experience. Great job thinking how you want to get the user to sign up initially.
- What seems to be lacking is the core product experience. I actually think that live video is less important. In fact, I think making this asynchronous would be much better.
- So, instead of doing live video, I think you guys should record video and/or audio and make it like a chat. The partner can then play the video whenever and reply.
- Try to incorporate the microphone so you can "verify" what they are trying to say. For example, the user should type "hey, how are you?", then they have to record themselves saying that line until they can pronounce it correctly.

### Engineering
- The challenge here is clearly the video. If you guys are doing live video, it'll be extremely hard. Please look at libraries/platforms that you can use.
- If you guys doing microphone, I think there will be a lot of interesting things you can do. Voice processing, etc. This is a very hot hot area right now.

**Comment by npke** [comment]
Hi Christ, Thank you so much for your feedback!
We considered all your ideas & suggestions. We have some solutions as following:

- To **enforce user to speaking English in the conversation**, use speech recognition to determine if user speak a not-English language then translate it to English & display it to help user continue the conversation, but user also be warned that if they speak not-English language more than three times in a conversation they will be banned (cannot use the make conversation feature), instead of that user should practice more before come back.

- **Record video and/or audio and make it like a chat**. All we think that this will bring a not good user experience because of the delay. User has to wait for the partner to record his video/audio and send it back. The waiting user may be distracted and quit the app if their partner has a slow response. However, video call forces them to watch to each other and have a quick response than chat. 

- **Verify the speech**. It's very good idea, thanks for giving it to us :). But instead of forcing them to pronoun the sentence until they can pronounce it correctly, we will give them point depend on the rate of correction. It will encourage them to practice more and try to get the maximum point.

- **Video chat**: We found some video chat services out there but haven't decided to use which one:
* [https://www.sinch.com](https://www.sinch.com)  
* [https://developers.oovoo.com/](https://developers.oovoo.com/)  
* [https://trueconf.com/](https://trueconf.com/)  
* [https://www.applozic.com](https://www.applozic.com)  
* [https://quickblox.com/developers/Sample-webrtc-android](https://quickblox.com/developers/Sample-webrtc-android)  
* [https://www.c2call.com/](https://www.c2call.com/)
Can you give us your suggestion?

Happy to see your feedback on our solutions soon!
